### ISSUE TITLE
Need a new tag for g2c cmake version

### ISSUE THREAD

**Issue by Hang-Lei-NOAA** [NOAA-EMC/NCEPLIBS-g2c#11]
We need a new tag for g2c  cmake version.
Please the code manager of g2c to create a tag and give a new version number for the latest update.
Please also remember to update the old version number in the readme.
Thanks

**Comment by edwardhartnett** [comment]
Let us do a release as outlined here: https://github.com/NOAA-EMC/NCEPLIBS/issues/131

So not just a tag, but a full release.

In practice, it won't make much difference since we don't have documentation to update, but let's get rolling on proper releases,

Does this library build from tarball, or does it depend on cmake code from other projects?

**Comment by Hang-Lei-NOAA** [comment]
It builds from tarball.
Yes, it needs a cmake version for NCO.

**Comment by edwardhartnett** [comment]
This version has been released, so I will close this issue.
