### ISSUE TITLE
CMake options of mixed case?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#21]
In the CMakeLists.txt for this project we have:

```
option(ENABLE_DOCS "Enable generation of doxygen-based documentation." OFF)
option(USE_PNG      "Use PNG library"      ON)
option(USE_Jasper   "Use Jasper library"   ON)
option(USE_OpenJPEG "Use OpenJPEG library" OFF)
```

Note that the last two options are mixed case. I'm not an expert on CMake (yet), but it seems all the options I've seen so far are all upper-case. Should we be following that convention with our options?

@kgerheiser  @aerorahul @mark-a-potts what do you guys think?

**Comment by aerorahul** [comment]
The mixed case use is because of the `find_package` convention for those packages.
For e.g. jasper can be found in cmake via `find_package(Jasper)`.  Internally, `find_package` searches for the Jasper library in locations such as `Jasper_ROOT`.
Same for `OpenJPEG`.  The CMake provided file to find these packages are `FindJasper.cmake`

**Comment by edwardhartnett** [comment]
OK, thanks for the explanation.
