### ISSUE TITLE
png support for 1, 2 or 4 bit depths?

### ISSUE THREAD

**Issue by webisu** [NOAA-EMC/NCEPLIBS-g2c#508]
Does g2c support png-encoded grib files with bit depths of  1, 2 or 4?

**Comment by DusanJovic-NOAA** [comment]
As far as I can tell, no. The reason is that in png decoding routine, if the image is encoded with less than 8 bits per pixel, this line:

```
174     bytes = bit_depth / 8;
175     clen = (*width) * bytes;
176     for (j = 0; j < *height; j++)
```
for `bit_depth` less than 8 (ie. 1, 2 or 4) will incorrectly set `bytes` to 0, and then `clen` will be 0, which is incorrect.

Instead, to support bit depths < 8, I think this should be changed to either `bytes = (width * nbits) / 8` or to  `bytes = (width * nbits) / 8 + 1` depending on whether width * bits is divisible by 8 or not.
And probably the loop that copies data from png arrays to g2c arrays needs to be changed as well.

I can try to update the code if we need to support this feature.

**Comment by DusanJovic-NOAA** [comment]
Are there sample files encoded with 1, 2 and 4 bit depths? Is this needed for production?

**Comment by webisu** [comment]
I have a sample file for 4 bits.   This problem was reported to wgrib2
support and
fixed 2021 by someone working for the USAF.  This is part of an effort to
get
wgrib2 to use the g2c code.  In order for this to happen, some g2c code need
to upgraded.  There will be another issue submitted to support larger grids
with
png.  OTOH wgrib2 will have to upgraded to support Jasper v2+.

**Comment by DusanJovic-NOAA** [comment]
See changes in #526
