### ISSUE TITLE
Determine what applications use the g2c library, and whether all the code the is necessary

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-g2c#53]
Determine what applications use the g2c library, and whether all the code the is necessary.

What apps use g2c?

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA and @DusanJovic-NOAA do you know what applications used the g2c library?

**Comment by DusanJovic-NOAA** [comment]
> @Hang-Lei-NOAA and @DusanJovic-NOAA do you know what applications used the g2c library?

I don't know.

**Comment by Hang-Lei-NOAA** [comment]
In EMC the wgrib2 lib use it.
This was a g2 lib in C language, which is used by pure C modules.

**Comment by BoiVuong-NOAA** [comment]
The g2c library uses in MET, GrADS, WGRIB2  and some users (out side of 
NCEP).

**Comment by edwardhartnett** [comment]
@BoiVuong-NOAA thanks - I believe GrADS has some unit testing - perhaps we can use that to test g2c until we get g2c unit testing in place. I will investigate.

**Comment by DusanJovic-NOAA** [comment]
We should find out whether NCO will use this repo's release next time they post the release tar file on their web page. If they are, then I suggest we rename this repo to just g2clib, Since most users are outside users it makes more sense to not have NCEPLIBS- prefix. NCEPLIBS is irrelevant to them. Most outside users refer to this library as just 'g2clib'.
